onEvent('block.loot_tables', event => {
	event.addSimpleBlock('byg:overgrown_crimson_blackstone', 'consistency_plus:cobbled_blackstone')
	event.addSimpleBlock('byg:overgrown_netherrack', 'consistency_plus:cobbled_netherrack')
	event.addSimpleBlock('byg:sythian_nylium', 'consistency_plus:cobbled_netherrack')
	event.addSimpleBlock('cinderscapes:umbral_nylium', 'consistency_plus:cobbled_netherrack')
	event.addSimpleBlock('minecraft:warped_nylium', 'consistency_plus:cobbled_netherrack')
	event.addSimpleBlock('minecraft:crimson_nylium', 'consistency_plus:cobbled_netherrack')
	event.addSimpleBlock('unearthed:overgrown_andesite', 'consistency_plus:cobbled_andesite')
	event.addSimpleBlock('unearthed:overgrown_granite', 'consistency_plus:cobbled_granite')
	event.addSimpleBlock('unearthed:overgrown_diorite', 'consistency_plus:cobbled_diorite')
})