generateOres = true
blacklistedOres = ["lead", "bauxite", "tin", "iridium", "tungsten"]
spawnWithGuideBook = true
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
